version: '2'

services:
  la-toolkit:
    image: la-toolkit
    container_name: la-toolkit
    restart: always
    hostname: la-toolkit
    build:
      context: .
      dockerfile: docker/u20/Dockerfile
    ports:
      - "20010:2010"
      - "20011-20100:20011-20100"
      # Internal an external ports should match in the previous range. 
      # So don't do these kind of redirections:
      # - "3011-3100:2011-2100"
    depends_on:
      - mongo
    environment:
      # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      # Useful for having logs with local time
      TZ: "Europe/Copenhagen"
      # db user/pass (should match the same mongo vars LA_USER/LA_PASS)
      DATABASE_URL: mongodb://la_toolkit_user:la_toolkit_changeme@mongo:27017/la_toolkit
      # Advanced optional URLs (useful to enable https and use a proxy)
      # TOOLKIT_SENTRY_DSN: "SOME_DSN",
      # TOOLKIT_PUBLIC_URL: "localhost:2010",
      # TOOLKIT_HTTPS : false
      # TOOLKIT_TERM_PROXY : false

    # The volumes should be writeable by your user so maybe you have to set your uid:gid here
    user: 1000:1000
    volumes:
      # mkdir -p /data/la-toolkit/config/ /data/la-toolkit/logs/ /data/la-toolkit/ssh/
      - /data/la-toolkit/config/:/home/ubuntu/ansible/la-inventories/:rw
      - /data/la-toolkit/logs/:/home/ubuntu/ansible/logs/:rw
      - /data/la-toolkit/ssh:/home/ubuntu/.ssh/:rw
      - ./build/web:/home/ubuntu/la-toolkit/assets/:ro
      # For 'custom' ala-install
      # Take into account that if your change from 'custom' to other ala-install version
      # code changes will be git stashed
      # - /data/la-toolkit/ala-install:/home/ubuntu/ansible/ala-install/:rw

  mongo:
    image: mongo:4
    restart: always
    container_name: la-toolkit-mongo
    # Uncomment if mongo-express is not enough
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: la_toolkit_mongo_admin
      MONGO_INITDB_ROOT_PASSWORD: la_toolkit_changeme
      MONGO_INITDB_DATABASE: la_toolkit
      LA_USER: la_toolkit_user
      LA_PASS: la_toolkit_changeme
    volumes:
      - ./docker/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - /data/la-toolkit/mongo:/data/db

  mongo-express:
    image: mongo-express
    container_name: la-toolkit-mongo-express
    restart: always
    ports:
      - 9081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: la_toolkit_mongo_admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: la_toolkit_changeme

  # 'watchtower' upgrade automatically the la-toolkit, whenever there is a new Docker image available,
  # but a container restart is also need to get the new image

  watchtower:
    image: containrrr/watchtower
    container_name: la-toolkit-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # Additional watchtower args
    # commmand:
