version: '2'

services:
  la-toolkit:
    image: livingatlases/la-toolkit:latest
    container_name: la-toolkit
    hostname: la-toolkit
    ports:
      - "2010:2010"
      - "2011-2100:2011-2100"
      # Internal an external ports should match in the previous range. 
      # So don't do these kind of redirections:
      # - "3011-3100:2011-2100"
    environment:
      # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      # Useful for having logs with local time
      TZ: "Australia/Canberra"
    volumes:
      # mkdir -p /data/la-toolkit/config/ /data/la-toolkit/logs/ /data/la-toolkit/ssh/
      - /data/la-toolkit/config/:/home/ubuntu/ansible/la-inventories/:rw
      - /data/la-toolkit/logs/:/home/ubuntu/ansible/logs/:rw
      - /data/la-toolkit/ssh:/home/ubuntu/.ssh/:rw
      # For 'custom' ala-install
      # - /data/la-toolkit/ala-install:/home/ubuntu/ansible/ala-install/:rw
