name: la_toolkit
description: Living Atlases Toolkit - Frontend

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

flutter-json:
  enable: true

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1
  google_fonts: ^1.1.2

  # ui
  introduction_screen: ^1.0.9
  flutter_linkify: ^4.0.2
  url_launcher: ^5.7.5
  flutter_markdown: ^0.5.2
  timelines: ^0.0.2+1
  responsive_grid: ^1.2.1+1
  feedback: ^0.3.0
  flutter_advanced_switch: ^0.0.9+4
  # Used for service selection (for instance in service deploy)
  chips_choice: ^2.0.1
  # Used by server service selection
  smart_select: ^4.3.2
  percent_indicator: ^2.1.9+1
  rflutter_alert: ^1.1.0
  xterm: ^1.1.1+1
  clipboard: ^0.1.2+8
  # loading spinner
  loader_overlay: ^1.1.1
  # used for terms
  modal_bottom_sheet: ^1.0.0+1
  web_browser: ^0.4.0
  # charts
  syncfusion_flutter_charts: ^18.4.46
  # bottom floating button
  flutter_speed_dial: ^3.0.4

  # icon
  mdi: ^5.0.0-nullsafety.0
  # font_awesome_flutter: ^8.11.0

  # data
  json_annotation: ^3.0.0
  copy_with_extension: ^1.4.0
  uuid: ^2.2.2
  http: ^0.12.2

  # Remove this in the future?
  shared_preferences: ^0.5.12+4

  # responsive framework and deps
  responsive_framework: ^0.0.14
  animations:  ^1.1.2

  # state
  flutter_redux: ^0.7.0
  redux_logging: ^0.4.0

  # utils
  flutter_dotenv: ^3.1.0
  package_info_plus: ^0.6.3
  dbcrypt: ^1.0.0
  cron: ^0.3.0

  # map
  flutter_map: ^0.11.0
  area: ^1.0.0

dev_dependencies:
  build_runner: ^1.11.1
  json_serializable: ^3.5.1
  copy_with_extension_gen: ^1.4.0
  test: ^1.16.0-nullsafety.9

  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env.development
    - .env.production
    - assets/images/la-icon.png
    - assets/images/ala-icon.png
    - assets/images/la-toolkit-intro-images-2.png
    - assets/images/la-toolkit-intro-images-3.png
    - assets/images/la-toolkit-intro-images-4.png
    - assets/images/la-toolkit-intro-images-5.png
    - assets/images/themes/clean.png
    - assets/images/themes/cosmo.png
    - assets/images/themes/darkly.png
    - assets/images/themes/flatly.png
    - assets/images/themes/material.png
    - assets/images/themes/paper.png
    - assets/images/themes/sandstone.png
    - assets/images/themes/simplex.png
    - assets/images/themes/slate.png
    - assets/images/themes/superhero.png
    - assets/images/themes/yeti.png

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family:  LAIcon
      fonts:
        - asset: fonts/LAIcon.ttf
